baseURL:            'https://sippy.cloud/'
languageCode:       'en-us'
title:              'Mellow'

markup:
  highlight:
    style:          'monokailight'
  goldmark:
    renderer:
      unsafe:       true

disableKinds:       ['taxonomy', 'term', 'RSS']
