baseURL:            'https://sippy.cloud/'
languageCode:       'en-us'
title:              'Mellow'

markup:
  highlight:
    style:          'monokailight'
  goldmark:
    renderer:
      unsafe:       true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

disableKinds:       ['taxonomy', 'term', 'RSS']
