name: CSS Bundlewatch
on:
  pull_request:

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run scss
        run: npm run scss
      - name: Run bundlewatch
        run: npm run bundlewatch
