name: CSS Bundlewatch
on:
  pull_request:

jobs:
  bundlewatch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run scss:compile
        run: npm run scss:compile
      - name: Run scss:prefix
        run: npm run scss:prefix
      - name: Run bundlewatch
        run: npm run bundlewatch
